=== AdamJozwiak/XML/Gwiazdka.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="JaIMojaPrzestrzeńNazw"
            xmlns:am="JaIMojaPrzestrzeńNazw"
            elementFormDefault="qualified">


    <xsd:element name="Gwiazdka">
        
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element type="xsd:string" name="tytuł"/>
                <xsd:element type="am:gwiazdyType" name="gwiazdy"/>
                <xsd:element type="am:gwiazdozbioryType" name="gwiazdozbiory"/>
            </xsd:sequence>
        </xsd:complexType>

        <xsd:key name="gwiazdozbiórID" >
            <xsd:selector xpath="./gwiazdozbiory/konstelacja"/>
             <xsd:field xpath="gwiazdozbiór"/>
         </xsd:key>

         <xsd:keyref name="gwiazdozbiórREF" refer="am:gwiazdozbiórID">
             <xsd:selector xpath="./gwiazdy/gwiazda"/>
             <xsd:field xpath="@gwiazdozbiór"/>
        </xsd:keyref>
        
    </xsd:element>

    <xsd:group name="gr">
        <xsd:sequence>
            <xsd:element type="am:masaType" name="masa"/>
            <xsd:element type="xsd:string" name="promień"/>
        </xsd:sequence>
    </xsd:group>

    <xsd:complexType name="gwiazdyType">
        <xsd:sequence>
            <xsd:element type="am:gwiazdaType" name="gwiazda" maxOccurs="unbounded" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="gwiazdozbioryType">
        <xsd:sequence>
            <xsd:element type="am:konstelacjaType" name="konstelacja" maxOccurs="unbounded" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="gwiazdaType">
        <xsd:sequence>
            <xsd:element type="xsd:string" name="nazwa"/>
            <xsd:element name="rodzaj">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="Karzeł"/>
                        <xsd:enumeration value="Olbrzym"/>
                        <xsd:enumeration value="Nadolbrzym"/>
                        <xsd:enumeration value="Podolbrzym"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element type="am:odległość_od_zType" name="odległość_od_z"/>
            <xsd:group ref="am:gr"/>
            <xsd:element type="xsd:string" name="data_odkrycia"/>
            <xsd:element type="am:wiekType" name="wiek"/>
            <xsd:element type="am:tempType" name="temp"/>
        </xsd:sequence>
        <xsd:attribute type="xsd:string" name="gwiazdozbiór"/>
    </xsd:complexType>

  <xsd:complexType name="odległość_od_zType" mixed="true">
    <xsd:attribute type="xsd:string" name="jednostka"/>
  </xsd:complexType>

  <xsd:complexType name="masaType" mixed="true">
    <xsd:sequence>
      <xsd:element type="xsd:integer" name="sup" minOccurs="0"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="wiekType" mixed="true">
    <xsd:sequence>
      <xsd:element name="sup" type="xsd:integer"/>
    </xsd:sequence>
  </xsd:complexType>
  
  <xsd:simpleType name="tempRestriction">
        <xsd:restriction base="xsd:integer">
            <xsd:minInclusive value="1"/>
            <xsd:maxInclusive value="100000"/>
        </xsd:restriction>
   </xsd:simpleType>

  <xsd:complexType name="tempType" >
      <xsd:simpleContent>
          <xsd:extension base="am:tempRestriction">
                <xsd:attribute type="xsd:string" name="jednostka"/>
          </xsd:extension>
      </xsd:simpleContent>
    
  </xsd:complexType>

  <xsd:complexType name="konstelacjaType">
      
    <xsd:sequence>
      <xsd:element type="xsd:string" name="nazwa"/>
      <xsd:element type="xsd:string" name="łacina"/>
      <xsd:element type="xsd:string" name="rektascensja"/>
      <xsd:element type="xsd:string" name="deklinacja"/>
      <xsd:element type="xsd:string" name="powierzchnia"/>
    </xsd:sequence>
    
    <xsd:attribute type="xsd:string" name="gwiazdozbiór"/>
    
  </xsd:complexType>

</xsd:schema>

=== AdamJozwiak/XML/Gwiazdka.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Gwiazdka.xsl"?>
<!--<?xml-stylesheet href="Gwiazdka.css" type="text/css"?>-->
<Gwiazdka>
	<!--xmlns="JaIMojaPrzestrzeńNazw"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="JaIMojaPrzestrzeńNazw Gwiazdka.xsd"-->

	<tytuł>Gwiazdy i Ich Konstelacje</tytuł>

		<gwiazdy>

			<gwiazda>
				<nazwa>Słońce</nazwa>
				<rodzaj>Karzeł</rodzaj>
				<odległość_od_z jednostka="ly">0,0000158</odległość_od_z>
				<masa>1,989*10<sup>30</sup> kg</masa>
				<promień>69600000 km</promień>
				<data_odkrycia>nieznana</data_odkrycia>
				<wiek>4,57*10<sup>9</sup>lat</wiek>
				<temp jednostka="K">5778 K</temp>
			</gwiazda>

			<gwiazda gwiazdozbiór="Wielki_Pies">
				<nazwa>Syriusz A</nazwa>
				<rodzaj>Karzeł</rodzaj>
				<odległość_od_z jednostka="ly">8,65</odległość_od_z>
				<masa>2,12 masy Słońca</masa>
				<promień>1,75 promienia Słońca</promień>
				<data_odkrycia>13.06.2459 p.n.e</data_odkrycia>
				<wiek>2,5*10<sup>8</sup>lat</wiek>
				<temp jednostka="K">9880 K</temp>
			</gwiazda>

			<gwiazda gwiazdozbiór="Wielki_Pies">
				<nazwa>Syriusz B</nazwa>
				<rodzaj>Karzeł</rodzaj> 
				<odległość_od_z jednostka="ly">8,6</odległość_od_z>
				<masa>1,03 masy Słońca</masa>
				<promień>1,03 promienia Słońca</promień>
				<data_odkrycia>13.06.1764 p.n.e</data_odkrycia>
				<wiek>3,5*10<sup>8</sup>lat</wiek>
				<temp jednostka="K">24800 K</temp>
			</gwiazda>

			<gwiazda gwiazdozbiór="Kil">
				<nazwa>Kanopus</nazwa>
				<rodzaj>Olbrzym</rodzaj>
				<odległość_od_z jednostka="ly">309</odległość_od_z>
				<masa>8,7 masy Słońca</masa>
				<promień>67,4 promienia Słońca</promień>
				<data_odkrycia>05.04.247 p.n.e</data_odkrycia>
				<wiek>7,8*10<sup>9</sup>lat</wiek>
				<temp jednostka="K">7280 K</temp>
			</gwiazda>

			<gwiazda gwiazdozbiór="Wolarz">
				<nazwa>Arktur</nazwa>
				<rodzaj>Olbrzym</rodzaj>
				<odległość_od_z jednostka="ly">36,72</odległość_od_z>
				<masa>1,8 masy Słońca</masa>
				<promień>25,4 promienia Słońca</promień>
				<data_odkrycia>14.02.1954</data_odkrycia>
				<wiek>7,1*10<sup>9</sup>lat</wiek>
				<temp jednostka="K">4286 K</temp>
			</gwiazda>

			<gwiazda gwiazdozbiór="Centaur">
				<nazwa>Alfa Centauri</nazwa>
				<rodzaj>Karzeł</rodzaj> 
				<odległość_od_z jednostka="ly">4,37</odległość_od_z>
				<masa>1,14 masy Słońca</masa>
				<promień>1,1 promienia Słońca</promień>
				<data_odkrycia>01.09.1856</data_odkrycia>
				<wiek>5,12*10<sup>9</sup>lat</wiek>
				<temp jednostka="K">5900 K</temp>
			</gwiazda>

			<gwiazda gwiazdozbiór="Lutnia">
				<nazwa>Wega</nazwa>
				<rodzaj>Karzeł</rodzaj>
				<odległość_od_z jednostka="ly">25,045</odległość_od_z>
				<masa>2,15 masy Słońca</masa>
				<promień>2,56 promienia Słońca</promień>
				<data_odkrycia>16.03.1301 p.n.e</data_odkrycia>
				<wiek>7*10<sup>8</sup>lat</wiek>
				<temp jednostka="K">9500 K</temp>
			</gwiazda>

			<gwiazda gwiazdozbiór="Orion">
				<nazwa>Rigel</nazwa>
				<rodzaj>Nadolbrzym</rodzaj> 
				<odległość_od_z jednostka="ly">870</odległość_od_z>
				<masa>23 masy Słońca</masa>
				<promień>78,9 promienia Słońca</promień>
				<data_odkrycia>16.07.1468</data_odkrycia>
				<wiek>8*10<sup>6</sup>lat</wiek>
				<temp jednostka="K">12100 K</temp>
			</gwiazda>

			<gwiazda gwiazdozbiór="Mały_Pies">
				<nazwa>Procjon A</nazwa>
				<rodzaj>Podolbrzym</rodzaj>
				<odległość_od_z jednostka="ly">11,462</odległość_od_z>
				<masa>1,42 masy Słońca</masa>
				<promień>2,1 promienia Słońca</promień>
				<data_odkrycia>03.04.1245 p.n.e</data_odkrycia>
				<wiek>1,7*10<sup>9</sup>lat</wiek>
				<temp jednostka="K">6530 K</temp>
			</gwiazda>

			<gwiazda gwiazdozbiór="Mały_Pies" >
				<nazwa>Procjon B</nazwa>
				<rodzaj>Karzeł</rodzaj> 
				<odległość_od_z jednostka="ly">11,41</odległość_od_z>
				<masa>0,6 masy Słońca</masa>
				<promień>1,35 promienia Słońca</promień>
				<data_odkrycia>07.04.1245 p.n.e</data_odkrycia>
				<wiek>9*10<sup>9</sup>lat</wiek>
				<temp jednostka="K">7440 K</temp>
			</gwiazda>

			<gwiazda gwiazdozbiór="Erydan">
				<nazwa>Achernar</nazwa>
				<rodzaj>Karzeł</rodzaj>
				<odległość_od_z jednostka="ly">139,4</odległość_od_z>
				<masa>7 mas Słońca</masa>
				<promień>11,6 promienia Słońca</promień>
				<data_odkrycia>16.10.1654 p.n.e</data_odkrycia>
				<wiek>6,87*10<sup>9</sup>lat</wiek>
				<temp jednostka="K">17000 K</temp>
			</gwiazda>

			<gwiazda gwiazdozbiór="Orion">
				<nazwa>Betelgeza</nazwa>
				<rodzaj>Nadolbrzym</rodzaj> 
				<odległość_od_z jednostka="ly">720</odległość_od_z>
				<masa>18 masy Słońca</masa>
				<promień>1000 promieni Słońca</promień>
				<data_odkrycia>09.11.1578 p.n.e</data_odkrycia>
				<wiek>8,5*10<sup>6</sup>lat</wiek>
				<temp jednostka="K">3600 K</temp>
			</gwiazda>

			<gwiazda gwiazdozbiór="Centaur">
				<nazwa>Hadar</nazwa>
				<rodzaj>Olbrzym</rodzaj> 
				<odległość_od_z jednostka="ly">400</odległość_od_z>
				<masa>14.7 masy Słońca</masa>
				<promień>9 promieni Słońca</promień>
				<data_odkrycia>12.07.1211 p.n.e</data_odkrycia>
				<wiek>14,2*10<sup>6</sup>lat</wiek>
				<temp jednostka="K">25000 K</temp>
			</gwiazda>

			<gwiazda gwiazdozbiór="Woźnica">
				<nazwa>Kapella</nazwa>
				<rodzaj>Olbrzym</rodzaj> 
				<odległość_od_z jednostka="ly">42,80</odległość_od_z>
				<masa>2,573 masy Słońca</masa>
				<promień>11,87 promienia Słońca</promień>
				<data_odkrycia>04.02.132</data_odkrycia>
				<wiek>4*10<sup>8</sup>lat</wiek>
				<temp jednostka="K">4920 K</temp>
			</gwiazda>

			<gwiazda gwiazdozbiór="Orzeł">
				<nazwa>Altair</nazwa>
				<rodzaj>Karzeł</rodzaj> 
				<odległość_od_z jednostka="ly">16,73</odległość_od_z>
				<masa>1,79 masy Słońca</masa>
				<promień>1,86 promienia Słońca</promień>
				<data_odkrycia>08.12.1367 p.n.e</data_odkrycia>
				<wiek>3,9*10<sup>9</sup>lat</wiek>
				<temp jednostka="K">7000 K</temp>
			</gwiazda>

			<gwiazda gwiazdozbiór="Byk">
				<nazwa>Aldebaran</nazwa>
				<rodzaj>Olbrzym</rodzaj>
				<odległość_od_z jednostka="ly">67</odległość_od_z>
				<masa>1,7 masy Słońca</masa>
				<promień>44,2 promienia Słońca</promień>
				<data_odkrycia>26.05.1412 p.n.e</data_odkrycia>
				<wiek>7,5*10<sup>9</sup>lat</wiek>
				<temp jednostka="K">4010 K</temp>
			</gwiazda>

			<gwiazda gwiazdozbiór="Panna">
				<nazwa>Spica</nazwa>
				<rodzaj>Podolbrzym</rodzaj> 
				<odległość_od_z jednostka="ly">250</odległość_od_z>
				<masa>10,25 masy Słońca</masa>
				<promień>7,40 promienia Słońca</promień>
				<data_odkrycia>27.09.1192 p.n.e</data_odkrycia>
				<wiek>6,45*10<sup>7</sup>lat</wiek>
				<temp jednostka="K">24000 K</temp>
			</gwiazda>

			<gwiazda gwiazdozbiór="Skorpion">
				<nazwa>Antares</nazwa>
				<rodzaj>Nadolbrzym</rodzaj> 
				<odległość_od_z jednostka="ly">550</odległość_od_z>
				<masa>17 mas Słońca</masa>
				<promień>883 promieni Słońca</promień>
				<data_odkrycia>23.11.475</data_odkrycia>
				<wiek>12*10<sup>6</sup>lat</wiek>
				<temp jednostka="K">3400 K</temp>
			</gwiazda>

			<gwiazda gwiazdozbiór="Bliźnięta">
				<nazwa>Polluks</nazwa>
				<rodzaj>Olbrzym</rodzaj> 
				<odległość_od_z jednostka="ly">33,785</odległość_od_z>
				<masa>1,47 masy Słońca</masa>
				<promień>9,3 promienia Słońca</promień>
				<data_odkrycia>11.07.984 p.n.e</data_odkrycia>
				<wiek>4,23*10<sup>7</sup>lat</wiek>
				<temp jednostka="K">4770 K</temp>
			</gwiazda>

			<gwiazda gwiazdozbiór="Ryba_Południowa">
				<nazwa>Fomalhaut</nazwa>
				<rodzaj>Karzeł</rodzaj> 
				<odległość_od_z jednostka="ly">25,126</odległość_od_z>
				<masa>1,92 masy Słońca</masa>
				<promień>1,842 promienia Słońca</promień>
				<data_odkrycia>31.12.654 p.n.e</data_odkrycia>
				<wiek>4,40*10<sup>8</sup>lat</wiek>
				<temp jednostka="K">8590 K</temp>
			</gwiazda>
		</gwiazdy>
		<!--
		<planety>

			<planeta typ="skalista">
				<nazwa>  Merkury  </nazwa>
				<miejsce_pol gwiazdozbiór="Układ Słoneczny" />
				<odległość_od_z> 90 mln km </odległość_od_z>
				<masa> 0,055 masy Ziemi</masa>
				<promień> 0,383 promienia Ziemi</promień>
				<okres_orb> 87,969 dni </okres_orb>
				<temp> ~500 K </temp>
			</planeta>

			<planeta typ="skalista">
				<nazwa>  Wenus  </nazwa>
				<miejsce_pol gwiazdozbiór="Układ Słoneczny" />
				<odległość_od_z> 40 - 259 mln </odległość_od_z>
				<masa> 0,815 masy Ziemi</masa>
				<promień> 0,902 promienia Ziemi</promień>
				<okres_orb> 224,701 dni </okres_orb>
				<temp> 737 K </temp>
			</planeta>

			<planeta typ="skalista">
				<nazwa>  Ziemia  </nazwa>
				<miejsce_pol gwiazdozbiór="Układ Słoneczny" />
				<odległość_od_z> XXX </odległość_od_z>
				<masa> 5,972*10<sup>24</sup> kg </masa>
				<promień> 6371 km </promień>
				<okres_orb> 365,25 dni </okres_orb>
				<temp> 185 - 331 K </temp>
			</planeta>

			<planeta typ="skalista">
				<nazwa>  Mars  </nazwa>
				<miejsce_pol gwiazdozbiór="Układ Słoneczny" />
				<odległość_od_z> 54 - 103 mln km </odległość_od_z>
				<masa> 0,107 masy Ziemi</masa>
				<promień> 0,532 promienia Ziemi</promień>
				<okres_orb> 686,98 dni </okres_orb>
				<temp> 133 - 293 K </temp>
			</planeta>

			<planeta typ="gazowa">
				<nazwa>  Jowisz  </nazwa>
				<miejsce_pol gwiazdozbiór="Układ Słoneczny" />
				<odległość_od_z> 591 - 965 mln km </odległość_od_z>
				<masa> 317,83 mas Ziemi</masa>
				<promień> 10,973 promienia Ziemi</promień>
				<okres_orb> 4332,589 dni </okres_orb>
				<temp> 165 K </temp>
			</planeta>

			<planeta typ="gazowa">
				<nazwa>  Saturn  </nazwa>
				<miejsce_pol gwiazdozbiór="Układ Słoneczny" />
				<odległość_od_z> 1,28 mld km </odległość_od_z>
				<masa> 95,16 masy Ziemi</masa>
				<promień> 9,140 promienia Ziemi</promień>
				<okres_orb> 10 759,22 dni </okres_orb>
				<temp> 134 K </temp>
			</planeta>

			<planeta typ="gazowa">
				<nazwa>  Uran  </nazwa>
				<miejsce_pol gwiazdozbiór="Układ Słoneczny" />
				<odległość_od_z> 2,721 mld km </odległość_od_z>
				<masa> 14,54 masy Ziemi</masa>
				<promień> 3,981 promienia Ziemi</promień>
